language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAIIT4U2WITBPBN3SA
  secret_access_key:
    secure: klKV+sIBdi2NMkqEHSPnHa5gg4tY5D7wNaTwYYJK4B/CXRsIIOqpxUSy2sUV5exOMnUANj2kAnTmlZXdUyx+eMbBcCSBCJ8gmctUcRlEeHiogSLTJMzNax9y59z4keIdr9TvIdilcYYR0pEP2uYXkTmZu3HArhEYj0VnDGNkEGVVwRlBG8KdqvU6UwXogGM6fKivV6MVAlHlQJkkwMkzrfDxpUo2l5NC0mJCkARoDqntcUmWGQGFrIlh3dSiI3v0FADawLMyVKY6QpJYnbPyI9C7Z9xOdyHDQO7uRr1XDaZe3j40uEjYR4KJolGJ0Iql8zE50qxbGnAj1opTvMmBOHYnxu+suuHkek9JAMrZmn6dxVcAOk5b7gxW7dbxgUtAq6rAKUKITNnE4ZVnlAH6Zo8jQOniYFKsVnFAvwq3EIrsZXVZ6yjUsJKFX/SZF3uw82aIItpV47xRmbPfvcOvLScNaNSj+x9a4YYETMqaYWl6b+wbSMsyx0HBwxSEXjBQejf5V+78zoisGjQQQIwZ1eoh7CRsuqbHS7/9AxBKaPEHFnbLVzluNRTkjmylc4rIJFnlg+JhJQvaRBU74ptj1+U1ZAMMWRtejhSZHnir4Va4zuppORZ1jiB7usaKQ6EHq/gPtmR2qxt7fBdF2MZRqYDa0Ps/RuJ5tl30Q3Jk2fA=
  bucket: revmuzik-frontend-build
  acl: public_read
